# Generated by Django 4.2.11 on 2026-03-30 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fixture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pronostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goles_local', models.PositiveSmallIntegerField()),
                ('goles_visitante', models.PositiveSmallIntegerField()),
                ('puntos_obtenidos', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pronosticos', to='fixture.partido')),
            ],
            options={
                'verbose_name': 'Pronóstico',
                'verbose_name_plural': 'Pronósticos',
            },
        ),
    ]
