# Generated by Django 4.2.11 on 2026-03-30 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pronosticos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pronostico',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pronosticos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='pronostico',
            unique_together={('usuario', 'partido')},
        ),
    ]
