# Generated by Django 4.2.11 on 2026-03-30 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fixture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoPremios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('balon_de_oro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balon_real', to='fixture.jugador')),
                ('bota_de_oro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bota_real', to='fixture.jugador')),
                ('guante_de_oro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guante_real', to='fixture.jugador')),
                ('mejor_joven', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='joven_real', to='fixture.jugador')),
            ],
            options={
                'verbose_name': 'Resultado premios',
                'verbose_name_plural': 'Resultado premios',
            },
        ),
        migrations.CreateModel(
            name='PronosticoPremio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_obtenidos', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('balon_de_oro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pronosticos_balon', to='fixture.jugador')),
                ('bota_de_oro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pronosticos_bota', to='fixture.jugador')),
                ('guante_de_oro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pronosticos_guante', to='fixture.jugador')),
                ('mejor_joven', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pronosticos_joven', to='fixture.jugador')),
            ],
            options={
                'verbose_name': 'Pronóstico de premios',
                'verbose_name_plural': 'Pronósticos de premios',
            },
        ),
    ]
