# Generated by Django 4.2.11 on 2026-03-30 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fixture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartidoEliminatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(choices=[('OCTAVOS', 'Octavos de final'), ('CUARTOS', 'Cuartos de final'), ('SEMIS', 'Semifinales'), ('TERCERO', 'Tercer puesto'), ('FINAL', 'Final')], max_length=10)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('fecha_hora', models.DateTimeField(blank=True, null=True)),
                ('estadio', models.CharField(blank=True, max_length=100)),
                ('goles_local', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('goles_visitante', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fue_a_extra', models.BooleanField(default=False)),
                ('fue_a_penales', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_JUEGO', 'En juego'), ('FINALIZADO', 'Finalizado')], default='PENDIENTE', max_length=12)),
            ],
            options={
                'verbose_name': 'Partido eliminatoria',
                'verbose_name_plural': 'Partidos eliminatorias',
                'ordering': ['fase', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='PronosticoEliminatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goles_local', models.PositiveSmallIntegerField()),
                ('goles_visitante', models.PositiveSmallIntegerField()),
                ('pronostica_extra', models.BooleanField(default=False)),
                ('pronostica_penales', models.BooleanField(default=False)),
                ('puntos_obtenidos', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ganador_pronosticado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pronosticos_ganador', to='fixture.equipo')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pronosticos', to='eliminatorias.partidoeliminatoria')),
            ],
        ),
    ]
