# Generated by Django 4.2.11 on 2026-03-30 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fixture', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eliminatorias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pronosticoeliminatoria',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pronosticos_elim', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partidoeliminatoria',
            name='equipo_local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elim_local', to='fixture.equipo'),
        ),
        migrations.AddField(
            model_name='partidoeliminatoria',
            name='equipo_visitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elim_visitante', to='fixture.equipo'),
        ),
        migrations.AddField(
            model_name='partidoeliminatoria',
            name='ganador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elim_ganadas', to='fixture.equipo'),
        ),
        migrations.AlterUniqueTogether(
            name='pronosticoeliminatoria',
            unique_together={('usuario', 'partido')},
        ),
    ]
