# Generated by Django 4.2.11 on 2026-04-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='codigo_iso',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
