# Generated by Django 4.2.11 on 2026-04-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixture', '0002_equipo_codigo_iso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='codigo_iso',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
