# Generated by Django 4.2.11 on 2026-04-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixture', '0003_alter_equipo_codigo_iso'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='id_externo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
