# Generated by Django 4.2.11 on 2026-04-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixture', '0004_jugador_id_externo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='id_externo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
